
version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports: 
      - '5432:5432' 
  web:
    build: .
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
    depends_on:
      - db