default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root
  host: db
  port: 5432

development:
  <<: *default
  database: loan_app_development

test:
  <<: *default
  database: loan_app_test

production:
  <<: *default
  database: loan_app_production

